# Command to start on workspace startup (optional)
tasks:
  - command: "cd && npm install -g --unsafe-perm node-red node-red-node-watson node-red-contrib-play-audio node-red-contrib-browser-utils node-red-dashboard node-red-contrib-deepl && mkdir .node-red && node-red flows.json"
    name: Node-RED
# Ports to expose on workspace startup (optional)
ports:
  - port: 1880
    onOpen: open-preview
